name: expense_tracker
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0-89.0.dev <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dropdown_button2: ^2.3.6
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  intl: ^0.18.1
  provider: ^6.0.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
